# Generated by Django 5.1.6 on 2025-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo do Livro')),
                ('author', models.CharField(max_length=255, verbose_name='Autor do Livro')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Livro')),
                ('instructions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instruções')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Capa do Livro')),
                ('public_data', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.ManyToManyField(to='book.category', verbose_name='Categoria do Livro')),
            ],
        ),
    ]
