# Generated by Django 5.1.6 on 2025-02-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
