# Generated by Django 5.1.6 on 2025-02-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
    ]
