# Generated by Django 5.1.6 on 2025-02-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_book_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='book.category', verbose_name='Categoria do Livro'),
        ),
    ]
