# Generated by Django 5.1.6 on 2025-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='instructions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instruções'),
        ),
    ]
