# Generated by Django 5.1.6 on 2025-02-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_days', models.IntegerField(default=30)),
                ('max_books_rented', models.IntegerField(default=3)),
            ],
        ),
    ]
