# Generated by Django 5.1.6 on 2025-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configrental',
            options={'verbose_name': 'Configuração de Aluguel', 'verbose_name_plural': 'Configurações de Aluguel'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Aluguel de Livro', 'verbose_name_plural': 'Aluguéis de Livros'},
        ),
        migrations.AlterField(
            model_name='configrental',
            name='max_books_rented',
            field=models.IntegerField(default=3, verbose_name='Quantidade Máxima de Livros Alugados'),
        ),
        migrations.AlterField(
            model_name='configrental',
            name='return_days',
            field=models.IntegerField(default=30, verbose_name='Tempo de Devolução (dias)'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Limite para Devolução'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data do Aluguel'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
    ]
