# Generated by Django 5.1.6 on 2025-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_configrental_max_books_rented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
